export enum ErrorCode {
  UNKNOWN_ERROR = 0,
  SYSTEM_STATS_REPOSITORY_WRITE_ERROR = 100,
  SYSTEM_STATS_REPOSITORY_READ_ERROR = 101,
  SYSTEM_STATS_REPOSITORY_CLEANUP_ERROR = 102,
  SYSTEM_WATCHER_GET_TEMPERATURE_ERROR = 200,
  SYSTEM_WATCHER_SAVE_STATS_ERROR = 201,
  SYSTEM_WATCHER_CLEANUP_STATS_ERROR = 202,
  MONITORING_SERVICE_GET_SYSTEM_STATS_ERROR = 300,
  BAD_REQUEST_PARAMETERS = 400,
  ENTITY_NOT_FOUND = 404,
  UNAUTHORIZED = 401,
}
